model:
  name: 'osnet_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['personx_spgan']
  targets: ['personx_spgan']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/osnet_4'

loss:
  name: 'triplet'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 70
  batch_size: 64
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False
  visrank: True